var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/lineup/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0heh61y._.js")
R.c("server/chunks/ssr/node_modules_next_dist_0ixdcs~._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0l-nmdk.js")
R.c("server/chunks/ssr/[root-of-the-server]__0mmnj9t._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0.angw.._.js")
R.c("server/chunks/ssr/node_modules_next_dist_compiled_0wewlb4._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0v73tbn._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/[root-of-the-server]__0wc~sd3._.js")
R.c("server/chunks/ssr/node_modules_next_dist_05~t7f3._.js")
R.c("server/chunks/ssr/node_modules_next_dist_0ve2ws3._.js")
R.c("server/chunks/ssr/_07g5r_x._.js")
R.m(11210)
module.exports=R.m(11210).exports
