var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/players/[id]/page.js")
R.c("server/chunks/ssr/node_modules_next_dist_060d1m.._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0ip6llc._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0m1vz3~.js")
R.c("server/chunks/ssr/node_modules_next_dist_0ixdcs~._.js")
R.c("server/chunks/ssr/node_modules_next_dist_0h5tz8r._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0mmnj9t._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0.angw.._.js")
R.c("server/chunks/ssr/node_modules_next_dist_compiled_0wewlb4._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0v73tbn._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/_next-internal_server_app_players_[id]_page_actions_0vbnaku.js")
R.m(29849)
module.exports=R.m(29849).exports
